# Generated by Django 5.2.12 on 2026-03-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ kiểm định'), ('IN_PROGRESS', 'Đang kiểm định'), ('COMPLETED', 'Hoàn thành — Đạt'), ('FAILED', 'Hoàn thành — Không đạt')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('quality_grade', models.CharField(blank=True, choices=[('A', 'Xuất sắc (A)'), ('B', 'Tốt (B)'), ('C', 'Trung bình (C)'), ('D', 'Kém (D)')], max_length=1, null=True, verbose_name='Phân loại chất lượng')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Điểm tổng')),
                ('conclusion', models.TextField(blank=True, verbose_name='Kết luận kiểm định')),
                ('recommendation', models.TextField(blank=True, verbose_name='Đề xuất hạng mục tân trang')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='Ngày kiểm định')),
                ('is_public', models.BooleanField(default=False, verbose_name='Hiển thị cho khách hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Phiếu kiểm định',
                'verbose_name_plural': 'Danh sách phiếu kiểm định',
                'db_table': 'inspection',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Danh mục kiểm định',
                'verbose_name_plural': 'Danh mục kiểm định',
                'db_table': 'inspection_category',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên hạng mục')),
                ('condition', models.CharField(choices=[('GOOD', 'Tốt'), ('FAIR', 'Bình thường'), ('POOR', 'Kém'), ('FAILED', 'Hỏng / Cần thay')], default='FAIR', max_length=20, verbose_name='Tình trạng')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Điểm (0–10)')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inspections/items/', verbose_name='Hình ảnh minh chứng')),
                ('needs_repair', models.BooleanField(default=False, verbose_name='Cần sửa chữa / tân trang')),
                ('estimated_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Chi phí sửa ước tính')),
            ],
            options={
                'verbose_name': 'Hạng mục kiểm định',
                'verbose_name_plural': 'Danh sách hạng mục kiểm định',
                'db_table': 'inspection_item',
                'ordering': ['category__display_order', 'name'],
            },
        ),
    ]
