# Generated by Django 5.2.12 on 2026-03-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ kiểm định'), ('IN_PROGRESS', 'Đang kiểm định'), ('COMPLETED', 'Hoàn thành'), ('FAILED', 'Không đạt')], default='PENDING', max_length=20)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note', models.TextField(blank=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('TOT', 'Tốt'), ('BINH_THUONG', 'Bình thường'), ('KEM', 'Kém')], default='BINH_THUONG', max_length=20)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inspection/')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ket_qua', models.CharField(choices=[('TOT', 'Tốt'), ('BINH_THUONG', 'Bình thường'), ('KEM', 'Kém')], default='BINH_THUONG', max_length=20, verbose_name='Kết quả')),
                ('diem', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Điểm đánh giá')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='inspection/results/', verbose_name='Hình ảnh minh chứng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
            ],
            options={
                'verbose_name': 'Kết quả kiểm định',
                'verbose_name_plural': 'Kết quả kiểm định',
            },
        ),
    ]
