# Generated by Django 5.2.12 on 2026-03-24 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_performed', to=settings.AUTH_USER_MODEL, verbose_name='Kỹ thuật viên kiểm định'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='vehicles.vehicleunit', verbose_name='Xe'),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inspections.inspectioncategory', verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.inspection', verbose_name='Phiếu kiểm định'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['vehicle'], name='inspection_vehicle_c0c789_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['status'], name='inspection_status_e9b326_idx'),
        ),
    ]
