-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.appointment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    customer_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    customer_phone character varying(15) COLLATE pg_catalog."default" NOT NULL,
    customer_email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    scheduled_at timestamp with time zone NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    note text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    customer_id bigint,
    handled_by_id bigint,
    vehicle_id bigint NOT NULL,
    CONSTRAINT appointment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.audit_log
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    action character varying(20) COLLATE pg_catalog."default" NOT NULL,
    model_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    object_id integer NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    old_value jsonb,
    new_value jsonb,
    ip_address inet,
    created_at timestamp with time zone NOT NULL,
    user_id bigint,
    CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.contact_inquiry
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    is_contacted boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT contact_inquiry_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.deposit
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    customer_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    customer_phone character varying(15) COLLATE pg_catalog."default" NOT NULL,
    customer_email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    amount numeric(14, 2) NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    note text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    momo_order_id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    momo_trans_id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    momo_pay_url character varying(500) COLLATE pg_catalog."default" NOT NULL,
    confirmed_by_id bigint,
    customer_id bigint,
    vehicle_id bigint NOT NULL,
    CONSTRAINT deposit_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.favorite
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    vehicle_id bigint NOT NULL,
    CONSTRAINT favorite_pkey PRIMARY KEY (id),
    CONSTRAINT favorite_user_id_vehicle_id_fdc41dc5_uniq UNIQUE (user_id, vehicle_id)
);

CREATE TABLE IF NOT EXISTS public.handover_record
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    handover_date timestamp with time zone NOT NULL,
    mileage_at_handover integer NOT NULL,
    note text COLLATE pg_catalog."default" NOT NULL,
    customer_signature character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL,
    staff_id bigint,
    sales_order_id bigint NOT NULL,
    CONSTRAINT handover_record_pkey PRIMARY KEY (id),
    CONSTRAINT handover_record_sales_order_id_key UNIQUE (sales_order_id)
);

CREATE TABLE IF NOT EXISTS public.inspection
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    quality_grade character varying(1) COLLATE pg_catalog."default",
    overall_score numeric(4, 1),
    conclusion text COLLATE pg_catalog."default" NOT NULL,
    recommendation text COLLATE pg_catalog."default" NOT NULL,
    inspection_date date,
    is_public boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    inspector_id bigint,
    vehicle_id bigint NOT NULL,
    CONSTRAINT inspection_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inspection_category
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    display_order smallint NOT NULL,
    CONSTRAINT inspection_category_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inspection_item
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    condition character varying(20) COLLATE pg_catalog."default" NOT NULL,
    score smallint,
    note text COLLATE pg_catalog."default" NOT NULL,
    image character varying(100) COLLATE pg_catalog."default",
    needs_repair boolean NOT NULL,
    estimated_repair_cost numeric(12, 2),
    category_id bigint,
    inspection_id bigint NOT NULL,
    CONSTRAINT inspection_item_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.listing
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    listed_price numeric(14, 2) NOT NULL,
    is_active boolean NOT NULL,
    is_featured boolean NOT NULL,
    views_count integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    vehicle_id bigint NOT NULL,
    CONSTRAINT listing_pkey PRIMARY KEY (id),
    CONSTRAINT listing_slug_key UNIQUE (slug),
    CONSTRAINT listing_vehicle_id_key UNIQUE (vehicle_id)
);

CREATE TABLE IF NOT EXISTS public.refurbishment_item
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    item_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    quantity smallint NOT NULL,
    unit_cost numeric(12, 2) NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    is_completed boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT refurbishment_item_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.refurbishment_order
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    note text COLLATE pg_catalog."default" NOT NULL,
    start_date date,
    completed_date date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    approved_by_id bigint,
    technician_id bigint,
    vehicle_id bigint NOT NULL,
    CONSTRAINT refurbishment_order_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sales_order
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    customer_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    customer_phone character varying(15) COLLATE pg_catalog."default" NOT NULL,
    sale_price numeric(14, 2) NOT NULL,
    contract_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    note text COLLATE pg_catalog."default" NOT NULL,
    sold_at timestamp with time zone NOT NULL,
    customer_id bigint,
    deposit_id bigint,
    sold_by_id bigint,
    vehicle_id bigint NOT NULL,
    CONSTRAINT sales_order_pkey PRIMARY KEY (id),
    CONSTRAINT sales_order_contract_number_key UNIQUE (contract_number),
    CONSTRAINT sales_order_vehicle_id_key UNIQUE (vehicle_id)
);

CREATE TABLE IF NOT EXISTS public.sell_inquiry
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    brand character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    year character varying(10) COLLATE pg_catalog."default" NOT NULL,
    mileage character varying(20) COLLATE pg_catalog."default" NOT NULL,
    expected_price character varying(50) COLLATE pg_catalog."default" NOT NULL,
    note text COLLATE pg_catalog."default" NOT NULL,
    is_contacted boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT sell_inquiry_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(15) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default" NOT NULL,
    avatar character varying(100) COLLATE pg_catalog."default",
    is_verified boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.users_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT users_groups_pkey PRIMARY KEY (id),
    CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.users_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.vehicle_media
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    file character varying(100) COLLATE pg_catalog."default" NOT NULL,
    media_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    is_primary boolean NOT NULL,
    caption character varying(200) COLLATE pg_catalog."default" NOT NULL,
    display_order smallint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    vehicle_id bigint NOT NULL,
    CONSTRAINT vehicle_media_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vehicle_pricing
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    purchase_price numeric(14, 0) NOT NULL,
    refurbish_cost numeric(14, 0) NOT NULL,
    other_cost numeric(14, 0) NOT NULL,
    target_price numeric(14, 0) NOT NULL,
    approved_price numeric(14, 0),
    note text COLLATE pg_catalog."default" NOT NULL,
    status character varying(10) COLLATE pg_catalog."default" NOT NULL,
    approved_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    approved_by_id bigint,
    created_by_id bigint,
    vehicle_id bigint NOT NULL,
    CONSTRAINT vehicle_pricing_pkey PRIMARY KEY (id),
    CONSTRAINT vehicle_pricing_vehicle_id_key UNIQUE (vehicle_id)
);

CREATE TABLE IF NOT EXISTS public.vehicle_spec
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    body_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    engine_capacity double precision,
    horsepower integer,
    doors smallint NOT NULL,
    seats smallint NOT NULL,
    origin character varying(20) COLLATE pg_catalog."default" NOT NULL,
    has_abs boolean NOT NULL,
    has_airbags boolean NOT NULL,
    airbag_count smallint NOT NULL,
    has_camera boolean NOT NULL,
    has_360_camera boolean NOT NULL,
    has_sunroof boolean NOT NULL,
    tire_condition character varying(50) COLLATE pg_catalog."default" NOT NULL,
    brake_condition character varying(50) COLLATE pg_catalog."default" NOT NULL,
    engine_condition character varying(50) COLLATE pg_catalog."default" NOT NULL,
    electrical_condition character varying(50) COLLATE pg_catalog."default" NOT NULL,
    vehicle_id bigint NOT NULL,
    CONSTRAINT vehicle_spec_pkey PRIMARY KEY (id),
    CONSTRAINT vehicle_spec_vehicle_id_key UNIQUE (vehicle_id)
);

CREATE TABLE IF NOT EXISTS public.vehicle_status_log
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    old_status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    new_status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    note text COLLATE pg_catalog."default" NOT NULL,
    changed_at timestamp with time zone NOT NULL,
    changed_by_id bigint,
    vehicle_id bigint NOT NULL,
    CONSTRAINT vehicle_status_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vehicle_unit
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    vin character varying(50) COLLATE pg_catalog."default" NOT NULL,
    license_plate character varying(20) COLLATE pg_catalog."default" NOT NULL,
    brand character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    variant character varying(100) COLLATE pg_catalog."default" NOT NULL,
    year integer NOT NULL,
    mileage integer NOT NULL,
    color character varying(50) COLLATE pg_catalog."default" NOT NULL,
    transmission character varying(20) COLLATE pg_catalog."default" NOT NULL,
    fuel_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    sale_price numeric(14, 2),
    description text COLLATE pg_catalog."default" NOT NULL,
    status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    purchase_price numeric(14, 2),
    purchase_date date,
    purchase_note text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    CONSTRAINT vehicle_unit_pkey PRIMARY KEY (id),
    CONSTRAINT vehicle_unit_vin_key UNIQUE (vin)
);

CREATE TABLE IF NOT EXISTS public.warranty_record
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    warranty_months smallint NOT NULL,
    max_mileage integer NOT NULL,
    coverage_note text COLLATE pg_catalog."default" NOT NULL,
    status character varying(10) COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    created_at timestamp with time zone NOT NULL,
    sales_order_id bigint NOT NULL,
    CONSTRAINT warranty_record_pkey PRIMARY KEY (id),
    CONSTRAINT warranty_record_sales_order_id_key UNIQUE (sales_order_id)
);

ALTER TABLE IF EXISTS public.appointment
    ADD CONSTRAINT appointment_customer_id_08843b56_fk_users_id FOREIGN KEY (customer_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS appointment_customer_id_08843b56
    ON public.appointment(customer_id);


ALTER TABLE IF EXISTS public.appointment
    ADD CONSTRAINT appointment_handled_by_id_2b77713e_fk_users_id FOREIGN KEY (handled_by_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS appointment_handled_by_id_2b77713e
    ON public.appointment(handled_by_id);


ALTER TABLE IF EXISTS public.appointment
    ADD CONSTRAINT appointment_vehicle_id_e487fbe6_fk_vehicle_unit_id FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicle_unit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS appointment_vehicle_7fd4e1_idx
    ON public.appointment(vehicle_id);


ALTER TABLE IF EXISTS public.audit_log
    ADD CONSTRAINT audit_log_user_id_a1b3392d_fk_users_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS audit_log_user_id_4dac76_idx
    ON public.audit_log(user_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.deposit
    ADD CONSTRAINT deposit_confirmed_by_id_eb4c78ec_fk_users_id FOREIGN KEY (confirmed_by_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS deposit_confirmed_by_id_eb4c78ec
    ON public.deposit(confirmed_by_id);


ALTER TABLE IF EXISTS public.deposit
    ADD CONSTRAINT deposit_customer_id_39bf0f1e_fk_users_id FOREIGN KEY (customer_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS deposit_customer_id_39bf0f1e
    ON public.deposit(customer_id);


ALTER TABLE IF EXISTS public.deposit
    ADD CONSTRAINT deposit_vehicle_id_b31c734e_fk_vehicle_unit_id FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicle_unit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS deposit_vehicle_568961_idx
    ON public.deposit(vehicle_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.favorite
    ADD CONSTRAINT favorite_user_id_8a5f8d2c_fk_users_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS favorite_user_id_8a5f8d2c
    ON public.favorite(user_id);


ALTER TABLE IF EXISTS public.favorite
    ADD CONSTRAINT favorite_vehicle_id_c8a4d7f5_fk_vehicle_unit_id FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicle_unit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS favorite_vehicle_id_c8a4d7f5
    ON public.favorite(vehicle_id);


ALTER TABLE IF EXISTS public.handover_record
    ADD CONSTRAINT handover_record_sales_order_id_286f2d28_fk_sales_order_id FOREIGN KEY (sales_order_id)
    REFERENCES public.sales_order (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS handover_record_sales_order_id_key
    ON public.handover_record(sales_order_id);


ALTER TABLE IF EXISTS public.handover_record
    ADD CONSTRAINT handover_record_staff_id_b1e28b9a_fk_users_id FOREIGN KEY (staff_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS handover_record_staff_id_b1e28b9a
    ON public.handover_record(staff_id);


ALTER TABLE IF EXISTS public.inspection
    ADD CONSTRAINT inspection_inspector_id_47ea85bd_fk_users_id FOREIGN KEY (inspector_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inspection_inspector_id_47ea85bd
    ON public.inspection(inspector_id);


ALTER TABLE IF EXISTS public.inspection
    ADD CONSTRAINT inspection_vehicle_id_c94740a4_fk_vehicle_unit_id FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicle_unit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inspection_vehicle_c0c789_idx
    ON public.inspection(vehicle_id);


ALTER TABLE IF EXISTS public.inspection_item
    ADD CONSTRAINT inspection_item_category_id_ac3f8cb9_fk_inspection_category_id FOREIGN KEY (category_id)
    REFERENCES public.inspection_category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inspection_item_category_id_ac3f8cb9
    ON public.inspection_item(category_id);


ALTER TABLE IF EXISTS public.inspection_item
    ADD CONSTRAINT inspection_item_inspection_id_4f258fac_fk_inspection_id FOREIGN KEY (inspection_id)
    REFERENCES public.inspection (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS inspection_item_inspection_id_4f258fac
    ON public.inspection_item(inspection_id);


ALTER TABLE IF EXISTS public.listing
    ADD CONSTRAINT listing_vehicle_id_123a9812_fk_vehicle_unit_id FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicle_unit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS listing_vehicle_id_key
    ON public.listing(vehicle_id);


ALTER TABLE IF EXISTS public.refurbishment_item
    ADD CONSTRAINT refurbishment_item_order_id_f28829fd_fk_refurbishment_order_id FOREIGN KEY (order_id)
    REFERENCES public.refurbishment_order (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS refurbishment_item_order_id_f28829fd
    ON public.refurbishment_item(order_id);


ALTER TABLE IF EXISTS public.refurbishment_order
    ADD CONSTRAINT refurbishment_order_approved_by_id_22ad31de_fk_users_id FOREIGN KEY (approved_by_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS refurbishment_order_approved_by_id_22ad31de
    ON public.refurbishment_order(approved_by_id);


ALTER TABLE IF EXISTS public.refurbishment_order
    ADD CONSTRAINT refurbishment_order_technician_id_52faec84_fk_users_id FOREIGN KEY (technician_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS refurbishment_order_technician_id_52faec84
    ON public.refurbishment_order(technician_id);


ALTER TABLE IF EXISTS public.refurbishment_order
    ADD CONSTRAINT refurbishment_order_vehicle_id_72dc1cb9_fk_vehicle_unit_id FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicle_unit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS refurbishme_vehicle_7dfe2d_idx
    ON public.refurbishment_order(vehicle_id);


ALTER TABLE IF EXISTS public.sales_order
    ADD CONSTRAINT sales_order_customer_id_798c889f_fk_users_id FOREIGN KEY (customer_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS sales_order_customer_id_798c889f
    ON public.sales_order(customer_id);


ALTER TABLE IF EXISTS public.sales_order
    ADD CONSTRAINT sales_order_deposit_id_7e2704c3_fk_deposit_id FOREIGN KEY (deposit_id)
    REFERENCES public.deposit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS sales_order_deposit_id_7e2704c3
    ON public.sales_order(deposit_id);


ALTER TABLE IF EXISTS public.sales_order
    ADD CONSTRAINT sales_order_sold_by_id_1561bbc2_fk_users_id FOREIGN KEY (sold_by_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS sales_order_sold_by_id_1561bbc2
    ON public.sales_order(sold_by_id);


ALTER TABLE IF EXISTS public.sales_order
    ADD CONSTRAINT sales_order_vehicle_id_86ce3633_fk_vehicle_unit_id FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicle_unit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS sales_order_vehicle_id_key
    ON public.sales_order(vehicle_id);


ALTER TABLE IF EXISTS public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS users_groups_group_id_2f3517aa
    ON public.users_groups(group_id);


ALTER TABLE IF EXISTS public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS users_groups_user_id_f500bee5
    ON public.users_groups(user_id);


ALTER TABLE IF EXISTS public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS users_user_permissions_permission_id_6d08dcd2
    ON public.users_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS users_user_permissions_user_id_92473840
    ON public.users_user_permissions(user_id);


ALTER TABLE IF EXISTS public.vehicle_media
    ADD CONSTRAINT vehicle_media_vehicle_id_b3030f7c_fk_vehicle_unit_id FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicle_unit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS vehicle_media_vehicle_id_b3030f7c
    ON public.vehicle_media(vehicle_id);


ALTER TABLE IF EXISTS public.vehicle_pricing
    ADD CONSTRAINT vehicle_pricing_approved_by_id_c19c72a2_fk_users_id FOREIGN KEY (approved_by_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS vehicle_pricing_approved_by_id_c19c72a2
    ON public.vehicle_pricing(approved_by_id);


ALTER TABLE IF EXISTS public.vehicle_pricing
    ADD CONSTRAINT vehicle_pricing_created_by_id_e2d33175_fk_users_id FOREIGN KEY (created_by_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS vehicle_pricing_created_by_id_e2d33175
    ON public.vehicle_pricing(created_by_id);


ALTER TABLE IF EXISTS public.vehicle_pricing
    ADD CONSTRAINT vehicle_pricing_vehicle_id_d96b43d8_fk_vehicle_unit_id FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicle_unit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS vehicle_pricing_vehicle_id_key
    ON public.vehicle_pricing(vehicle_id);


ALTER TABLE IF EXISTS public.vehicle_spec
    ADD CONSTRAINT vehicle_spec_vehicle_id_9d6be63f_fk_vehicle_unit_id FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicle_unit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS vehicle_spec_vehicle_id_key
    ON public.vehicle_spec(vehicle_id);


ALTER TABLE IF EXISTS public.vehicle_status_log
    ADD CONSTRAINT vehicle_status_log_changed_by_id_62ab160d_fk_users_id FOREIGN KEY (changed_by_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS vehicle_status_log_changed_by_id_62ab160d
    ON public.vehicle_status_log(changed_by_id);


ALTER TABLE IF EXISTS public.vehicle_status_log
    ADD CONSTRAINT vehicle_status_log_vehicle_id_8df72d65_fk_vehicle_unit_id FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicle_unit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS vehicle_status_log_vehicle_id_8df72d65
    ON public.vehicle_status_log(vehicle_id);


ALTER TABLE IF EXISTS public.vehicle_unit
    ADD CONSTRAINT vehicle_unit_created_by_id_7114ce11_fk_users_id FOREIGN KEY (created_by_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS vehicle_unit_created_by_id_7114ce11
    ON public.vehicle_unit(created_by_id);


ALTER TABLE IF EXISTS public.warranty_record
    ADD CONSTRAINT warranty_record_sales_order_id_1fc03c48_fk_sales_order_id FOREIGN KEY (sales_order_id)
    REFERENCES public.sales_order (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS warranty_record_sales_order_id_key
    ON public.warranty_record(sales_order_id);

END;