# Generated by Django 5.2.12 on 2026-03-24 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=50, unique=True, verbose_name='Số khung (VIN nội bộ)')),
                ('license_plate', models.CharField(blank=True, max_length=20, verbose_name='Biển số xe')),
                ('brand', models.CharField(db_index=True, max_length=100, verbose_name='Hãng xe')),
                ('model', models.CharField(max_length=100, verbose_name='Dòng xe')),
                ('variant', models.CharField(blank=True, max_length=100, verbose_name='Phiên bản')),
                ('year', models.PositiveIntegerField(verbose_name='Năm sản xuất')),
                ('mileage', models.PositiveIntegerField(verbose_name='Số km đã đi')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Màu sắc')),
                ('transmission', models.CharField(choices=[('MANUAL', 'Số sàn'), ('AUTOMATIC', 'Số tự động'), ('CVT', 'CVT')], max_length=20, verbose_name='Hộp số')),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Xăng'), ('DIESEL', 'Dầu diesel'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Điện')], max_length=20, verbose_name='Nhiên liệu')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá bán niêm yết')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả xe')),
                ('status', models.CharField(choices=[('PURCHASED', 'Mới thu mua'), ('WAIT_INSPECTION', 'Chờ kiểm định'), ('INSPECTING', 'Đang kiểm định'), ('INSPECTED', 'Đã kiểm định'), ('WAIT_REFURBISH', 'Chờ tân trang'), ('REFURBISHING', 'Đang tân trang'), ('READY_FOR_SALE', 'Sẵn sàng bán'), ('LISTED', 'Đang đăng bán'), ('RESERVED', 'Đã giữ chỗ (đặt cọc)'), ('SOLD', 'Đã bán'), ('WARRANTY', 'Đang bảo hành')], db_index=True, default='PURCHASED', max_length=30, verbose_name='Trạng thái')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá thu mua')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Ngày thu mua')),
                ('purchase_note', models.TextField(blank=True, verbose_name='Ghi chú thu mua')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo hồ sơ')),
            ],
            options={
                'verbose_name': 'Xe',
                'verbose_name_plural': 'Danh sách xe',
                'db_table': 'vehicle_unit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('PURCHASED', 'Mới thu mua'), ('WAIT_INSPECTION', 'Chờ kiểm định'), ('INSPECTING', 'Đang kiểm định'), ('INSPECTED', 'Đã kiểm định'), ('WAIT_REFURBISH', 'Chờ tân trang'), ('REFURBISHING', 'Đang tân trang'), ('READY_FOR_SALE', 'Sẵn sàng bán'), ('LISTED', 'Đang đăng bán'), ('RESERVED', 'Đã giữ chỗ (đặt cọc)'), ('SOLD', 'Đã bán'), ('WARRANTY', 'Đang bảo hành')], max_length=30, verbose_name='Trạng thái trước')),
                ('new_status', models.CharField(choices=[('PURCHASED', 'Mới thu mua'), ('WAIT_INSPECTION', 'Chờ kiểm định'), ('INSPECTING', 'Đang kiểm định'), ('INSPECTED', 'Đã kiểm định'), ('WAIT_REFURBISH', 'Chờ tân trang'), ('REFURBISHING', 'Đang tân trang'), ('READY_FOR_SALE', 'Sẵn sàng bán'), ('LISTED', 'Đang đăng bán'), ('RESERVED', 'Đã giữ chỗ (đặt cọc)'), ('SOLD', 'Đã bán'), ('WARRANTY', 'Đang bảo hành')], max_length=30, verbose_name='Trạng thái mới')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm thay đổi')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='vehicles.vehicleunit', verbose_name='Xe')),
            ],
            options={
                'verbose_name': 'Lịch sử trạng thái xe',
                'verbose_name_plural': 'Lịch sử trạng thái xe',
                'db_table': 'vehicle_status_log',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(blank=True, choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('CUV', 'CUV'), ('HATCHBACK', 'Hatchback'), ('MPV', 'MPV'), ('PICKUP', 'Bán tải'), ('COUPE', 'Coupe'), ('CROSSOVER', 'Crossover')], max_length=20, verbose_name='Kiểu dáng xe')),
                ('engine_capacity', models.FloatField(blank=True, null=True, verbose_name='Dung tích động cơ (L)')),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True, verbose_name='Công suất (HP)')),
                ('doors', models.PositiveSmallIntegerField(default=4, verbose_name='Số cửa')),
                ('seats', models.PositiveSmallIntegerField(default=5, verbose_name='Số chỗ ngồi')),
                ('origin', models.CharField(blank=True, choices=[('DOMESTIC', 'Trong nước'), ('IMPORTED', 'Nhập khẩu')], max_length=20, verbose_name='Xuất xứ')),
                ('has_abs', models.BooleanField(default=False, verbose_name='Phanh ABS')),
                ('has_airbags', models.BooleanField(default=False, verbose_name='Túi khí')),
                ('airbag_count', models.PositiveSmallIntegerField(default=0, verbose_name='Số túi khí')),
                ('has_camera', models.BooleanField(default=False, verbose_name='Camera lùi')),
                ('has_360_camera', models.BooleanField(default=False, verbose_name='Camera 360')),
                ('has_sunroof', models.BooleanField(default=False, verbose_name='Cửa sổ trời')),
                ('tire_condition', models.CharField(blank=True, max_length=50, verbose_name='Tình trạng lốp')),
                ('brake_condition', models.CharField(blank=True, max_length=50, verbose_name='Tình trạng phanh')),
                ('engine_condition', models.CharField(blank=True, max_length=50, verbose_name='Tình trạng động cơ')),
                ('electrical_condition', models.CharField(blank=True, max_length=50, verbose_name='Tình trạng hệ thống điện')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='vehicles.vehicleunit', verbose_name='Xe')),
            ],
            options={
                'verbose_name': 'Thông số kỹ thuật',
                'verbose_name_plural': 'Thông số kỹ thuật',
                'db_table': 'vehicle_spec',
            },
        ),
        migrations.CreateModel(
            name='VehicleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vehicles/media/', verbose_name='File')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Hình ảnh'), ('VIDEO', 'Video')], default='IMAGE', max_length=10, verbose_name='Loại media')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ảnh đại diện')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='vehicles.vehicleunit', verbose_name='Xe')),
            ],
            options={
                'verbose_name': 'Media xe',
                'verbose_name_plural': 'Media xe',
                'db_table': 'vehicle_media',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicleunit',
            index=models.Index(fields=['brand'], name='vehicle_uni_brand_dccf69_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleunit',
            index=models.Index(fields=['status'], name='vehicle_uni_status_91fb1b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleunit',
            index=models.Index(fields=['year'], name='vehicle_uni_year_935d40_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleunit',
            index=models.Index(fields=['sale_price'], name='vehicle_uni_sale_pr_0208cb_idx'),
        ),
    ]
