# Generated by Django 5.2.12 on 2026-03-07 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('MANUAL', 'Số sàn'), ('AUTOMATIC', 'Số tự động')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Xăng'), ('DIESEL', 'Dầu'), ('HYBRID', 'Hybrid'), ('ELECTRIC', 'Điện')], max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PURCHASED', 'Mới nhập'), ('WAIT_INSPECTION', 'Chờ kiểm định'), ('INSPECTED', 'Đã kiểm định'), ('READY_FOR_SALE', 'Sẵn sàng bán'), ('LISTED', 'Đang đăng bán'), ('SOLD', 'Đã bán')], default='PURCHASED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('PURCHASED', 'Mới nhập'), ('WAIT_INSPECTION', 'Chờ kiểm định'), ('INSPECTED', 'Đã kiểm định'), ('READY_FOR_SALE', 'Sẵn sàng bán'), ('LISTED', 'Đang đăng bán'), ('SOLD', 'Đã bán')], max_length=30)),
                ('new_status', models.CharField(choices=[('PURCHASED', 'Mới nhập'), ('WAIT_INSPECTION', 'Chờ kiểm định'), ('INSPECTED', 'Đã kiểm định'), ('READY_FOR_SALE', 'Sẵn sàng bán'), ('LISTED', 'Đang đăng bán'), ('SOLD', 'Đã bán')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='vehicles.vehicleunit')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_capacity', models.FloatField(blank=True, null=True)),
                ('body_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('HATCHBACK', 'Hatchback'), ('PICKUP', 'Pickup')], max_length=50)),
                ('doors', models.IntegerField(default=4)),
                ('seats', models.IntegerField(default=5)),
                ('origin', models.CharField(blank=True, choices=[('TRONG_NUOC', 'Trong nước'), ('NHAP_KHAU', 'Nhập khẩu')], max_length=50)),
                ('has_abs', models.BooleanField(default=False)),
                ('has_airbags', models.BooleanField(default=False)),
                ('has_camera', models.BooleanField(default=False)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='vehicles.vehicleunit')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vehicles/')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Hình ảnh'), ('VIDEO', 'Video')], default='IMAGE', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='vehicles.vehicleunit')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicleunit',
            index=models.Index(fields=['brand'], name='vehicles_ve_brand_3afcb4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleunit',
            index=models.Index(fields=['status'], name='vehicles_ve_status_fc55b0_idx'),
        ),
    ]
