# Generated by Django 5.2.12 on 2026-03-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefurbishmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên hạng mục')),
                ('item_type', models.CharField(choices=[('LABOR', 'Nhân công'), ('PARTS', 'Phụ tùng / vật liệu'), ('OTHER', 'Khác')], default='PARTS', max_length=10, verbose_name='Loại chi phí')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Đơn giá')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Đã hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Hạng mục tân trang',
                'verbose_name_plural': 'Danh sách hạng mục tân trang',
                'db_table': 'refurbishment_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefurbishmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('IN_PROGRESS', 'Đang tân trang'), ('COMPLETED', 'Hoàn thành — Đã nghiệm thu'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Lệnh tân trang',
                'verbose_name_plural': 'Danh sách lệnh tân trang',
                'db_table': 'refurbishment_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
