# Generated by Django 5.2.12 on 2026-03-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefurbishmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên hạng mục')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Chi phí')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Hạng mục sửa chữa',
                'verbose_name_plural': 'Danh sách hạng mục sửa chữa',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefurbishmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('IN_PROGRESS', 'Đang sửa chữa'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú sửa chữa')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày bắt đầu')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Lệnh sửa chữa',
                'verbose_name_plural': 'Danh sách lệnh sửa chữa',
                'ordering': ['-created_at'],
            },
        ),
    ]
