# Generated by Django 5.2.12 on 2026-03-24 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refurbishment', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refurbishmentorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refurbishments_approved', to=settings.AUTH_USER_MODEL, verbose_name='Người nghiệm thu'),
        ),
        migrations.AddField(
            model_name='refurbishmentorder',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_refurbishments', to=settings.AUTH_USER_MODEL, verbose_name='Kỹ thuật viên phụ trách'),
        ),
        migrations.AddField(
            model_name='refurbishmentorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refurbishment_orders', to='vehicles.vehicleunit', verbose_name='Xe cần tân trang'),
        ),
        migrations.AddField(
            model_name='refurbishmentitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='refurbishment.refurbishmentorder', verbose_name='Lệnh tân trang'),
        ),
        migrations.AddIndex(
            model_name='refurbishmentorder',
            index=models.Index(fields=['status'], name='refurbishme_status_4115b4_idx'),
        ),
        migrations.AddIndex(
            model_name='refurbishmentorder',
            index=models.Index(fields=['vehicle'], name='refurbishme_vehicle_7dfe2d_idx'),
        ),
    ]
