# Generated by Django 5.2.12 on 2026-03-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền đặt cọc')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Đã xác nhận')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Đặt cọc',
                'verbose_name_plural': 'Đặt cọc',
                'db_table': 'deposit',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề bài đăng')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug SEO')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('listed_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá bán niêm yết')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Bài đăng bán xe',
                'verbose_name_plural': 'Bài đăng bán xe',
                'db_table': 'listing',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá mua vào')),
                ('refurbish_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Chi phí tân trang')),
                ('suggested_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá đề xuất bán')),
                ('approved_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá đã được duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Định giá xe',
                'verbose_name_plural': 'Định giá xe',
                'db_table': 'pricing',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá bán thực tế')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Số hợp đồng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú giao dịch')),
                ('sold_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm bán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Đơn bán xe',
                'verbose_name_plural': 'Đơn bán xe',
                'db_table': 'sales_order',
            },
        ),
    ]
