# Generated by Django 5.2.12 on 2026-03-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('scheduled_at', models.DateTimeField(verbose_name='Thời gian hẹn')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('COMPLETED', 'Đã xem xe'), ('CANCELLED', 'Đã hủy'), ('NO_SHOW', 'Không đến')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Lịch hẹn xem xe',
                'verbose_name_plural': 'Danh sách lịch hẹn',
                'db_table': 'appointment',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('DELETE', 'Xóa'), ('STATUS_CHANGE', 'Thay đổi trạng thái'), ('APPROVE', 'Phê duyệt'), ('REJECT', 'Từ chối')], max_length=20, verbose_name='Hành động')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model bị tác động')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID đối tượng')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Giá trị trước')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Giá trị sau')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm thực hiện')),
            ],
            options={
                'verbose_name': 'Nhật ký thao tác',
                'verbose_name_plural': 'Nhật ký thao tác',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Nội dung')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Đã liên hệ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
            ],
            options={
                'verbose_name': 'Thông tin liên hệ',
                'verbose_name_plural': 'Thông tin liên hệ',
                'db_table': 'contact_inquiry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Số tiền đặt cọc')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận — Xe đã khóa'), ('CANCELLED', 'Đã hủy'), ('REFUNDED', 'Đã hoàn cọc'), ('CONVERTED', 'Đã chuyển thành đơn bán')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt cọc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('momo_order_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='MoMo Order ID')),
                ('momo_trans_id', models.CharField(blank=True, default='', max_length=64, verbose_name='MoMo Transaction ID')),
                ('momo_pay_url', models.URLField(blank=True, default='', max_length=500, verbose_name='MoMo Payment URL')),
            ],
            options={
                'verbose_name': 'Đặt cọc',
                'verbose_name_plural': 'Danh sách đặt cọc',
                'db_table': 'deposit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
            ],
            options={
                'verbose_name': 'Xe yêu thích',
                'verbose_name_plural': 'Xe yêu thích',
                'db_table': 'favorite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_date', models.DateTimeField(verbose_name='Ngày giờ bàn giao')),
                ('mileage_at_handover', models.PositiveIntegerField(verbose_name='Số km tại thời điểm bàn giao')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú bàn giao')),
                ('customer_signature', models.ImageField(blank=True, null=True, upload_to='handovers/signatures/', verbose_name='Chữ ký khách hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Biên bản bàn giao xe',
                'verbose_name_plural': 'Biên bản bàn giao xe',
                'db_table': 'handover_record',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề bài đăng')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Đường dẫn SEO')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('listed_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Giá niêm yết')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Xe nổi bật')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Bài đăng bán xe',
                'verbose_name_plural': 'Bài đăng bán xe',
                'db_table': 'listing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Tên người mua')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Giá bán thực tế')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Số hợp đồng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú giao dịch')),
                ('sold_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm bán')),
            ],
            options={
                'verbose_name': 'Đơn bán xe',
                'verbose_name_plural': 'Danh sách đơn bán xe',
                'db_table': 'sales_order',
                'ordering': ['-sold_at'],
            },
        ),
        migrations.CreateModel(
            name='SellInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Hãng xe')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Dòng xe')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='Năm SX')),
                ('mileage', models.CharField(blank=True, max_length=20, verbose_name='Số km')),
                ('expected_price', models.CharField(blank=True, max_length=50, verbose_name='Giá mong muốn')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='Đã liên hệ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
            ],
            options={
                'verbose_name': 'Yêu cầu bán xe',
                'verbose_name_plural': 'Yêu cầu bán xe',
                'db_table': 'sell_inquiry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Giá thu mua (đ)')),
                ('refurbish_cost', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Chi phí tân trang (đ)')),
                ('other_cost', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Chi phí khác (đ)')),
                ('target_price', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Giá bán đề xuất (đ)')),
                ('approved_price', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Giá bán được duyệt (đ)')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ phê duyệt'), ('APPROVED', 'Đã phê duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=10, verbose_name='Trạng thái')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phiếu định giá',
                'db_table': 'vehicle_pricing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_months', models.PositiveSmallIntegerField(default=6, verbose_name='Thời hạn bảo hành (tháng)')),
                ('max_mileage', models.PositiveIntegerField(default=10000, verbose_name='Số km tối đa bảo hành')),
                ('coverage_note', models.TextField(blank=True, verbose_name='Nội dung bảo hành')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang bảo hành'), ('EXPIRED', 'Hết hạn'), ('VOID', 'Đã hủy')], default='ACTIVE', max_length=10, verbose_name='Trạng thái')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu bảo hành')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc bảo hành')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Hồ sơ bảo hành',
                'verbose_name_plural': 'Hồ sơ bảo hành',
                'db_table': 'warranty_record',
            },
        ),
    ]
