# Generated by Django 5.2.12 on 2026-03-24 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_handled', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên xử lý'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vehicles.vehicleunit', verbose_name='Xe muốn xem'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên xác nhận'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='vehicles.vehicleunit', verbose_name='Xe đặt cọc'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='vehicles.vehicleunit', verbose_name='Xe yêu thích'),
        ),
        migrations.AddField(
            model_name='handoverrecord',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên bàn giao'),
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='vehicles.vehicleunit', verbose_name='Xe'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng mua'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order', to='sales.deposit', verbose_name='Đặt cọc liên quan'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên bán hàng'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order', to='vehicles.vehicleunit', verbose_name='Xe được bán'),
        ),
        migrations.AddField(
            model_name='handoverrecord',
            name='sales_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='sales.salesorder', verbose_name='Đơn bán hàng'),
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricings_approved', to=settings.AUTH_USER_MODEL, verbose_name='Người phê duyệt'),
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricings_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='vehiclepricing',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='vehicles.vehicleunit', verbose_name='Xe'),
        ),
        migrations.AddField(
            model_name='warrantyrecord',
            name='sales_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='sales.salesorder', verbose_name='Đơn bán hàng'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['vehicle'], name='appointment_vehicle_7fd4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appointment_status_7a6b08_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_at'], name='appointment_schedul_1019be_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='audit_log_model_n_c04ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='audit_log_user_id_4dac76_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='audit_log_created_5a7975_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['vehicle'], name='deposit_vehicle_568961_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['status'], name='deposit_status_dd441d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'vehicle')},
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_active'], name='listing_is_acti_3835a8_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listed_price'], name='listing_listed__6a2f35_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_featured'], name='listing_is_feat_39bf60_idx'),
        ),
    ]
