# Generated by Django 5.2.12 on 2026-03-07 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dat_coc_xe', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dat_coc', to='vehicles.vehicleunit', verbose_name='Xe được đặt cọc'),
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bai_dang', to='vehicles.vehicleunit', verbose_name='Xe'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gia_da_duyet', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dinh_gia', to='vehicles.vehicleunit', verbose_name='Xe'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_mua_xe', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='don_ban', to='vehicles.vehicleunit', verbose_name='Xe được bán'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['vehicle'], name='deposit_vehicle_568961_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['customer'], name='deposit_custome_e96b78_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['confirmed'], name='deposit_confirm_73510e_idx'),
        ),
        migrations.AddIndex(
            model_name='deposit',
            index=models.Index(fields=['created_at'], name='deposit_created_b25f93_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_active'], name='listing_is_acti_3835a8_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listed_price'], name='listing_listed__6a2f35_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['created_at'], name='listing_created_753d65_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['sold_at'], name='sales_order_sold_at_d1a145_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer'], name='sales_order_custome_62a3d7_idx'),
        ),
    ]
