# Generated by Django 5.2.12 on 2026-03-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warrantyrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hồ sơ bảo hành', 'verbose_name_plural': 'Hồ sơ bảo hành'},
        ),
    ]
